// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrPGtDDA7dtso8AWZrQxrdlxJIfIDoda4',
    appId: '1:485128541717:web:d30eb152676f55aac7601c',
    messagingSenderId: '485128541717',
    projectId: 'jobappfirebase-82b4d',
    authDomain: 'jobappfirebase-82b4d.firebaseapp.com',
    storageBucket: 'jobappfirebase-82b4d.appspot.com',
    measurementId: 'G-6BDDPNJZLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIlglCGAtlxSvKaKp7lUDLsC5zTjAdNq8',
    appId: '1:485128541717:android:aa3cfdf477b159a2c7601c',
    messagingSenderId: '485128541717',
    projectId: 'jobappfirebase-82b4d',
    storageBucket: 'jobappfirebase-82b4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU3aVS7CUaUr38xa-au36eFIz7rtbg3b4',
    appId: '1:485128541717:ios:a0c804f091af4fa9c7601c',
    messagingSenderId: '485128541717',
    projectId: 'jobappfirebase-82b4d',
    storageBucket: 'jobappfirebase-82b4d.appspot.com',
    iosBundleId: 'com.example.jobappfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU3aVS7CUaUr38xa-au36eFIz7rtbg3b4',
    appId: '1:485128541717:ios:670315b9421de248c7601c',
    messagingSenderId: '485128541717',
    projectId: 'jobappfirebase-82b4d',
    storageBucket: 'jobappfirebase-82b4d.appspot.com',
    iosBundleId: 'com.example.jobappfirebase.RunnerTests',
  );
}
